### ISSUE TITLE
TEST CASES IMPLEMENTATION (fileIO try/except)

### ISSUE THREAD

**Issue by sphills** [loglug1/CS325-project4#7]
# Test Case 5: Error handling for write_data()
### Branch 6c8786d

Please confirm that this try/except implementation looks okay and handles the error adequately.

**Comment by loglug1** [comment]
I would try not to write the error to the file since if there was an exception when writing the article to the file it's a high chance that writing the error would also cause an exception. Also FileIO is independent of the CNN scraper and should not contain language pertaining to it.

**Comment by sphills** [comment]
Sounds good, I'll remove it and close the issue :+1:
