### ISSUE TITLE
TEST CASES IMPLEMENTATION (run.py try/except)

### ISSUE THREAD

**Issue by sphills** [loglug1/CS325-project4#8]
# Test Case 6: Error handling for FileIO(args.file_in)
### Branch https://github.com/loglug1/CS325-project4/commit/91263e03ab4b99b2f78b9bc24662dc06030baa6f

Please confirm that this try/except implementation looks okay and handles the error adequately.

**Comment by loglug1** [comment]
I don't think the constructor for the FileIO class will raise an exception since it only saves the filename to a variable instead of actually opening the file for read or write.

**Comment by loglug1** [comment]
This could be moved to the write file or read file methods to actually catch the error.

**Comment by sphills** [comment]
Alrighty, I've moved it to the later output calls to catch failed writing errors. Closing.
