### ISSUE TITLE
TEST CASES IMPLEMENTATION (fileIO casting test)

### ISSUE THREAD

**Issue by sphills** [loglug1/CS325-project4#9]
# Test Case 7: Error handling for write_data()
### Branch c4ccbed

Commented a question about casting a list of strings to string instead of to int.

**Comment by loglug1** [comment]
This code was meant to just be something to throw in the main of the module. It shouldn't run normally. Casting to a string was a quick and dirty way to get proper formatting of a list as a string.

**Comment by sphills** [comment]
Sounds good, testing the logic of the cast and your answer for it makes sense to me.
